version: '2'
services:
    air-elk:
        container_name: air-elk
        image: sebp/elk
        # volumes:
        ports:
            - 5044:5044
            - 5601:5601
            - 9200:9200
            - 9300:9300