- hosts: localhost
  vars:
    projectFolder: /Users/rtsypuk/projects/personal/airtraffic/
    airtrafficApp: airtraffic_app
    airtrafficMysql: airtraffic_mysql
    airtrafficELK: airtraffic_elk

  tasks:
  - name: 'Removing old APP images.'
    command: bash -lc  "docker rmi {{airtrafficApp}}"
    ignore_errors: yes

  - name: 'Removing old mysql images.'
    command: bash -lc  "docker rmi {{airtrafficMysql}}"
    ignore_errors: yes

  - name: 'Removing old ELK images.'
    command: bash -lc  "docker rmi {{airtrafficELK}}"
    ignore_errors: yes

  - name: 'Clean up dangling images.'
    command: bash -lc "docker rmi $(docker images --filter \""dangling=true\"" -q --no-trunc)"
    ignore_errors: yes

  - name: 'Building Docker Image for airtraffic_app.'
    command: bash -lc  "cd {{projectFolder}} && docker build --rm --label {{airtrafficApp}} -t '{{airtrafficApp}}:latest' ."

  - name: 'Building Docker Image for airtraffic_mysql.'
    command: bash -lc  "cd {{projectFolder}}src/main/docker/images/mysql && docker build --rm --label {{airtrafficMysql}} -t '{{airtrafficMysql}}:latest' ."

  - name: 'Building Docker Image for airtraffic_elk.'
    command: bash -lc  "cd {{projectFolder}}src/main/docker/images/elk && docker build --rm --label {{airtrafficELK}} -t '{{airtrafficELK}}:latest' ."

  - name: 'Running Docker compose.'
    command: bash -lc  "docker-compose -f {{projectFolder}}src/main/docker/app.yml up -d"